Feature favorite
codestates-seb/seb39_main_022 pull request #31
Opened 2022-09-23 06:56 UTC by General-code

즐겨찾기 기능을 추가했습니다.

2022-09-23 06:57 UTC, General-code commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +
static factory method로 postDto에 of를 구현해서 바로 생성하게 했는데 컨트롤러 단에서 생성해서 문제가 되는 걸까요?

2022-09-23 10:33 UTC, Hyune-c requested changes

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/resources/application.yml
> +    password: ${DATASOURCE_PASSWORD:root}
차후 환경 변수로 뺼 수 있는 좋은 방법이네요. 👍

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/member/entity/Member.java
>  }
eof

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/utils/WheelCenterUtils.java
> +public abstract class WheelCenterUtils {
abstract 를 사용한 의도를 잘 모르겠습니다. 
어떤 이유가 있나요?

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +    public FavoritePlaceResponseDto createFavoritePlace(@SessionAttribute(LOGIN_MEMBER)Member member,
session 활용 👍

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +        return responseDto;
```suggestion
        return service.createFavoritePlace(
                FavoritePlacePostDto.of(favoritePlacePostDto, member, wheelCenterId));
```

`nit`

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +                                                        @RequestBody @Validated FavoritePlacePostDto favoritePlacePostDto) {
```suggestion
                                                        @RequestBody @Validated FavoritePlacePostDto dto) {
```
`nit`

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +    public List<FavoritePlaceResponseDto> getFavoritePlaces(@SessionAttribute(LOGIN_MEMBER)Member member)
- 보안적으로도 매우 중요한 member entity 가 노출되고 있습니다.
- 영속성 레이어의 객체가 web 까지도 노출되고 있습니다.

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/service/FavoritePlaceService.java
> +        });
`nit` 한줄로 처리할 수 있을 것 같습니다.

2022-09-23 10:33 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/favoritePlace/controller/FavoritePlaceController.java
> +
매개변수를 보니 dto, entity, value 까지 모두 있네요.
어떤 문제가 있으신거 같으신가요.

2022-09-27 12:15 UTC, Hyune-c approved these changes

2022-09-28 01:46 UTC, merged