Feature serch ldk
codestates-seb/seb39_main_022 pull request #32
Opened 2022-09-23 07:16 UTC by Limdongkeun

현재 검색에 관련된 기능을 도, 시, 군, 구, 동 이름으로 각자 검색하는 것과 한 번에 처리 할 수 있게 하는것으로 만들어뒀습니다 프론트쪽이랑 상의 후 한 번에 처리하는 것만 남겨둘 계획입니다 

추후 controller에서 사용된 mapper를 서비스레이어로 변경하는 리팩토링 진행예정입니다

2022-09-23 10:41 UTC, Hyune-c requested changes

2022-09-23 10:41 UTC, Hyune-c commented on server/wheelmaster/src/main/generated/main/wheelmaster/comment/mapper/CommentMapperImpl.java
>  @Component
이게 뭔가 했는데 generated 경로가 git 에 올라오고 있네요.
gitignore 해주세요.

2022-09-23 10:41 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
> +                                                  @Positive @PathParam("size") int size){
pageable 을 활용할 수 있는 방법도 있습니다.

2022-09-23 10:41 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
>      @GetMapping("/cityName")
cityName, roadAddress, oldAddress

- city 는 네이밍에 name 이 들어있네요. 이게 의도한 리소스 인가요?
- Address 는 구분이 road 와 old 네요. 이것이 서로 의도한 구분이 되나요?

2022-09-23 10:41 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/service/WheelCenterService.java
> +    }
매개변수 부터 PageRequest 로 받으면 어떨까요.

2022-09-25 05:16 UTC, Limdongkeun commented on server/wheelmaster/src/main/generated/main/wheelmaster/comment/mapper/CommentMapperImpl.java
>  @Component
네 주의하겠습니다

2022-09-25 05:19 UTC, Limdongkeun commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
>      @GetMapping("/cityName")
- cityName은 서울특별시,인천광역시,강원도,충청북도 등을 나태냈고
- roadAddress 는 도로명주소
- oldAddress는 지번주도(무슨 동) 이렇게 된걸 표시했습니다

2022-09-25 05:20 UTC, Limdongkeun commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/service/WheelCenterService.java
> +    }
pageable과 함께 찾아보고 수정하겠습니다

2022-09-25 05:55 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
>      @GetMapping("/cityName")
첫번째 질문은 의도적으로 추상적으로 했습니다.
조금 더 구체적으로 질문해보겠습니다. 
다시 생각을 말해주세요.

> city 는 네이밍에 name 이 들어있네요. 이게 의도한 리소스 인가요?
- 의도한 리소스의 단위가 city 일까요? name 일까요?
- 이 개념에 따라 이어지는 질문에 대한 흐름도 달라집니다.

> Address 는 구분이 road 와 old 네요. 이것이 서로 의도한 구분이 되나요?
- road 와 old 라는 단어는 서로 상반되지 않습니다.
- 아마 신 주소 형태인 `도로명 주소` 방식과 구 주소 형태의 `지번 주소` 의 구분을 의도하신 것 같습니다.
- 저는 이와 비슷한 업무를 해본적이 있기에 배경 없이도 이해할 수 있었지만, 배경 지식이 없는 사람은 이해하기 힘듭니다.

---

코드를 일관성있게 작성하기 위해서는 도메인 정의가 일관성 있어야 한다고 생각합니다.
굉장히 어려운 개념이 맞으니 잘 이해가 안된다고 해도 괜찮습니다.

2022-09-26 02:38 UTC, Limdongkeun commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
>      @GetMapping("/cityName")
- CityName에 포함된 내용이 서울특별시,인천광영시,강원도,충청북도...등을 포함하고 있어 우리나라 행정구역 표기볍으로 Do(도)를 나타내거나 Metropolitan City(특별시,광역시)등을 나타내는 용어로 바꾸는게 맞다고 생각됩니다
- 저희가 의도한 CityName은 도,광역시,특별시 등을 나타내려고 했던건대 맞지 않다고 생각됩니다

- `도로명 주소`는 Road Name Address로 , `지번 주소`는 Lot number Address 라고 표기한다고 찾아봤습니다 
- Lot이 행정구역을 나눌때 해당위치의 지번주소를 사용한다는 글을 봤습니다

2022-09-27 12:25 UTC, Hyune-c commented on server/wheelmaster/src/main/java/main/wheelmaster/wheelcenter/controller/searchController.java
>      @GetMapping("/cityName")
네. 어느정도 생각이 정리된거 같으시니 제 의견을 첨부합니다.

- 리소스는 city 여야지, name 은 리소스의 부속 개념이라고 생각합니다. `GET /city/{city_id}/name`
- 네. 저도 roadNameAdress 와 lotNumberAddress 를 의도했습니다.
    - 만약 old 를 사용하고 싶다면, old 와 new 로 했을 것 같습니다.
    - 물론 old, new 두 종류만 표현하다는 단점이 있습니다. 하지만 그 이상 늘어나지 않을 것으로 간주할 수 있다면 이것도 나쁘지 않다고 생각합니다.

2022-09-30 06:44 UTC, merged